USE LoteriaDB

--CARGA INICIAL--

IF(SELECT COUNT(*)
FROM Carta) = 0
BEGIN
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Gallo', '/01-Gallo.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Diablito', '/02-Diablito.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Dama', '/03-LaDama.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Catrin', '/04-ElCatrin.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Paraguas', '/05-ElParaguas.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Sirena', '/06-LaSirena.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Escalera', '/07-LaEscalera.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Botella', '/08-LaBotella.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Barril', '/09-ElBarril.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Arbol', '/10-ElArbol.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Melon', '/11-ElMelon.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Borracho', '/12-ElBorracho.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Gorrito', '/13-ElGorrito.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Muerte', '/14-LaMuerte.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Pera', '/15-LaPera.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Bandera', '/16-LaBandera.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Bandolon', '/17-ElBandolon.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Violoncello', '/18-ElVioloncello.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Garza', '/19-LaGarza.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Pajaro', '/20-ElPajaro.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Mano', '/21-LaMano.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Bota', '/22-LaBota.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Luna', '/23-LaLuna.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Cotorro', '/24-ElCotorro.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Borracho', '/25-ElBorracho.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Negrito', '/26-ElNegrito.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Corazon', '/27-ElCorazon.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Sandia', '/28-LaSandia.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Tambor', '/29-ElTambor.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Camaron', '/30-ElCamaron.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('Las Jaras', '/31-LasJaras.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Musico', '/32-ElMusico.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Arana', '/33-LaArana.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Soldado', '/34-ElSoldado.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Estrella', '/35-LaEstrella.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Cazo', '/36-ElCazo.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Mundo', '/37-ElMundo.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Apache', '/38-ElApache.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Nopal', '/39-ElNopal.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Alacran', '/40-ElAlacran.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Rosa', '/41-LaRosa.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Calavera', '/42-LaCalavera.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Campana', '/43-LaCampana.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Cantarito', '/44-ElCantarito.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Venado', '/45-ElVenado.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Sol', '/46-ElSol.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Corona', '/47-LaCorona.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Chalupa', '/48-LaChalupa.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Pino', '/49-ElPino.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Pescado', '/50-ElPescado.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Palma', '/51-LaPalma.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Maceta', '/52-LaMaceta.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('El Arpa', '/53-ElArpa.png')
	INSERT INTO Carta(Descripcion, Imagen) VALUES('La Rana', '/54-LaRana.png')
END
